# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.
main:
  - name: Bio
    url: /
    weight: 10
  - name: Projects
    url: projects/
    weight: 11
  - name: Publications
    url: publications/
    weight: 12
  # - name: Papers
  #   url: /#papers
  #   weight: 13
  - name: Talks
    url: /#talks
    weight: 14
  # - name: News
  #   url: /#news
  #   weight: 15
  - name: Experience         #<<---- FIRST COMPILE MY METHODS, THEN UPLOAD THIS
    url: experience/
    weight: 16
  - name: Teaching
    url: courses/
    weight: 17
    
# # Navigation Links
# #   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#   #     desired widget in your `content/home/` folder.
#   #   The weight parameter defines the order that the links will appear in.
# 
# main:
#   - name: Bio
#     url: /
#     weight: 10
#   - name: Projects
#     url: projects/
#     weight: 11
#   - name: Papers
#     url: /#papers
#     weight: 12
#   - name: Talks
#     url: /#talks
#     weight: 13
#   # - name: News
#   #   url: /#news
#   #   weight: 13
#   # - name: Methods         <<---- FIRST COMPILE MY METHODS, THEN UPLOAD THIS
#   #   url: experience/
#   #   weight: 14
#   - name: Teaching
#     url: courses/
#     weight: 14
